### PR TITLE
Ike support

### PR DESCRIPTION
**Pull request by ltv511**
Add IKE support on ports 500 and 4500 over UDP.

### CODE REVIEW

**Comment by fliphil** [comment]
Thank you for this submission! There's a lot to look through, so that will take a bit of time. One thing I did notice though is that there isn't any documentation for the functions in ike.c. Is that something you can provide (in Doxygen format)?

**Comment by ltv511** [comment]
Sure! I left out comments for most of the functions since the function names are mostly self-explanatory, but I suppose more comments never hurt. I'm happy to fix anything else that you find as well!

**Comment by fliphil** [comment]
When I run with the test pcaps that you included, I see that some of the values are empty quotes like so: "spi": "". Would it be better to not print out that key/value pair at all if the value is empty? The Internet suggest that if we need to keep the empty values then it would be best to use null as the value. @banderson84 What is your opinion?

**Comment by bhudson33** [comment]
@filphil, in other parts of Joy, if there is not value we do not print out the item. Unless there is a valid reason to keep the item with a null value, I would suggest not printing the item.

**Comment by ltv511** [comment]
Yep, that makes sense. I can make the changes.

**Comment by davidmcgrew** [comment]
Hi Bill,

**Comment by fliphil** [comment]
Thank you for those changes!
I think you're good to merge this in. Just a heads up, we'll probably be asking for some changes to the way the JSON is structured in the near future due to plans for redoing the schema. Is that okay with you?

**Comment by ltv511** [comment]
Okay, sounds good! Sure, it shouldn't be a problem to restructure the JSON output later on. (The same goes for the ssh module.)

**Pull request merged**
